[package]
name = "rpnc"
version = "0.1.0"
authors = ["yayoc <hi@yayoc.com>"]
license = "MIT"
description = "Reverse Polish Notation Calculator"
edition = "2018"
repository = "https://github.com/yayoc/rpnc"

[[bin]]
name = "rpnc"
doc = false
path = "src/main.rs"
